DELIMITER $$
CREATE DEFINER=`wms-user`@`localhost` PROCEDURE `getAllStationSensorByStationID`(IN `st_id` INT)
    NO SQL
SELECT  SS.STATION_SENSOR_ID, SLIST.SENSOR_NAME, SLIST.STATUS, SL.STATION_ID, SL.STATION_NAME
FROM STATION_SENSOR SS, STATION_LIST SL, SENSOR_LIST SLIST
WHERE SS.STATION_ID = SL.STATION_ID AND SS.SENSOR_ID = SLIST.SENSOR_ID
AND SL.STATION_ID = st_id$$
DELIMITER ;