DELIMITER $$
CREATE DEFINER=`wms-user`@`%` PROCEDURE `getAllStationList`()
    NO SQL
SELECT SL.*, ST.STATION_TYPE_NAME FROM STATION_LIST SL, STATION_TYPE ST WHERE SL.STATION_TYPE_ID = ST.STATION_TYPE_ID$$
DELIMITER ;