DELIMITER $$
CREATE DEFINER=`wms-user`@`localhost` PROCEDURE `getStationByID`(IN `st_id` INT)
    NO SQL
SELECT SL.*, ST.STATION_TYPE_NAME FROM STATION_LIST SL, STATION_TYPE ST WHERE SL.STATION_TYPE_ID = ST.STATION_TYPE_ID AND SL.STATION_ID = st_id$$
DELIMITER ;